/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import management.Evaluation;

/**
 *
 * @author Ahmed
 */
public class AddEvaluationFrame extends javax.swing.JFrame {

    Evaluation Ev;

    /**
     * Creates new form AddEvaluationFrame
     */
    public AddEvaluationFrame() {
        Ev = new Evaluation();
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdELabel = new javax.swing.JLabel();
        IdE = new javax.swing.JTextField();
        IdM = new javax.swing.JTextField();
        IdCLabel2 = new javax.swing.JLabel();
        TypeNoteLabel = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        Note = new javax.swing.JTextField();
        NoteLabel = new javax.swing.JLabel();
        TypeNote = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(22, 129, 255));
        jPanel3.setForeground(new java.awt.Color(22, 129, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tCampus-125.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enregistrer une Evaluation");

        IdELabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        IdELabel.setForeground(new java.awt.Color(255, 255, 255));
        IdELabel.setText("Identifiant de l'Etudiant (CIN/Passport)");

        IdE.setBackground(new java.awt.Color(138, 192, 255));
        IdE.setBorder(null);

        IdM.setBackground(new java.awt.Color(138, 192, 255));
        IdM.setBorder(null);
        IdM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdMKeyTyped(evt);
            }
        });

        IdCLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        IdCLabel2.setForeground(new java.awt.Color(255, 255, 255));
        IdCLabel2.setText("Identifiant de la Matière");

        TypeNoteLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        TypeNoteLabel.setForeground(new java.awt.Color(255, 255, 255));
        TypeNoteLabel.setText("Type de la Note");

        message2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        message2.setForeground(new java.awt.Color(255, 255, 255));

        SaveBtn.setBackground(new java.awt.Color(138, 192, 255));
        SaveBtn.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(18, 66, 129));
        SaveBtn.setText("Enregistrer");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        Note.setBackground(new java.awt.Color(138, 192, 255));
        Note.setBorder(null);
        Note.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoteKeyTyped(evt);
            }
        });

        NoteLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        NoteLabel.setForeground(new java.awt.Color(255, 255, 255));
        NoteLabel.setText("Note");

        TypeNote.setBackground(new java.awt.Color(138, 192, 255));
        TypeNote.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        TypeNote.setForeground(new java.awt.Color(0, 0, 0));
        TypeNote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DS", "Examen", "TP" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdE)
                            .addComponent(IdCLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NoteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Note)
                            .addComponent(TypeNote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IdM, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(IdELabel)
                .addGap(5, 5, 5)
                .addComponent(IdE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(IdCLabel2)
                .addGap(5, 5, 5)
                .addComponent(IdM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TypeNoteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TypeNote, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoteLabel)
                .addGap(5, 5, 5)
                .addComponent(Note, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if (this.verifCoordonnees() == -1) {
            return;
        }
        String IdEIn = IdE.getText().trim();
        int IdMIn = Integer.valueOf(IdM.getText());
        String type = TypeNote.getSelectedItem().toString();
        float note = Float.valueOf(Note.getText());
        Ev.ajouter(IdEIn, IdMIn, note, type);
        this.dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void IdMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdMKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_IdMKeyTyped

    private void NoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoteKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_NoteKeyTyped
    public void displayError(String reason) {
        JFrame frame = new JFrame("Error Dialog");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JOptionPane.showMessageDialog(frame, reason, "Erreur", JOptionPane.ERROR_MESSAGE);

        frame.dispose();
    }

    public int verifCoordonnees() {
        String IdEIn = IdE.getText().trim();
        int IdMIn = Integer.valueOf(IdM.getText());
        float note = Float.valueOf(Note.getText());
        if (IdEIn == "") {
            displayError("Vous devez taper l'identifiant de l'etudiant");
            return -1;
        }
        if (IdMIn <= 0) {
            displayError("Vous devez taper l'identifiant de la matiere");
            return -1;
        }
        if(note <0 || note >20){
            displayError("Une note doit être comprise entre 0 et 20");
            return -1;
        }

        return 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdCLabel2;
    private javax.swing.JTextField IdE;
    private javax.swing.JLabel IdELabel;
    private javax.swing.JTextField IdM;
    private javax.swing.JTextField Note;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> TypeNote;
    private javax.swing.JLabel TypeNoteLabel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel message2;
    // End of variables declaration//GEN-END:variables
}
