package Frame;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import management.Enseignant;


public class AjouterEnseignantFrame extends javax.swing.JFrame {

    
    ImageIcon savedImageIcon = new javax.swing.ImageIcon(getClass().getResource("/photo_profile.jpg"));

    public AjouterEnseignantFrame() {
        initComponents();
        
        this.setResizable(false);
                      setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cnss = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FileUploaded = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        upload = new javax.swing.JButton();
        PhotoLabel = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        day = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        year = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fonction = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        prenom1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cinpassport = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        SaveButton1 = new javax.swing.JButton();
        username1 = new javax.swing.JTextField();

        setTitle("Modifier un étudiant");
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 156, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(16, 58, 171));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajouter un Enseignant");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 410, 45);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'utilistateur");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(32, 172, 422, 35);

        cnss.setBackground(new java.awt.Color(187, 206, 255));
        cnss.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cnss.setForeground(new java.awt.Color(0, 0, 0));
        cnss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnssActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cnss);
        cnss.setBounds(260, 550, 200, 42);

        email.setBackground(new java.awt.Color(187, 206, 255));
        email.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(email);
        email.setBounds(32, 337, 422, 39);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(32, 290, 422, 35);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mot de passe");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(32, 394, 422, 35);

        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Prénom");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(515, 43, 252, 35);

        prenom.setBackground(new java.awt.Color(187, 206, 255));
        prenom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(prenom);
        prenom.setBounds(515, 84, 252, 39);

        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nom");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(773, 43, 220, 35);

        nom.setBackground(new java.awt.Color(187, 206, 255));
        nom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(nom);
        nom.setBounds(773, 84, 220, 39);

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Genre");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(515, 147, 252, 19);

        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tél/Mobile");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(770, 320, 220, 19);

        tel.setBackground(new java.awt.Color(187, 206, 255));
        tel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(tel);
        tel.setBounds(770, 350, 220, 41);

        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Photo");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(530, 280, 138, 38);

        FileUploaded.setBackground(new java.awt.Color(187, 206, 255));
        FileUploaded.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        FileUploaded.setForeground(new java.awt.Color(0, 0, 0));
        FileUploaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileUploadedActionPerformed(evt);
            }
        });
        kGradientPanel1.add(FileUploaded);
        FileUploaded.setBounds(769, 471, 160, 40);

        genre.setBackground(new java.awt.Color(187, 206, 255));
        genre.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        genre.setForeground(new java.awt.Color(0, 0, 0));
        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        kGradientPanel1.add(genre);
        genre.setBounds(515, 172, 252, 42);

        password.setBackground(new java.awt.Color(187, 206, 255));
        password.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(password);
        password.setBounds(32, 435, 422, 43);

        upload.setBackground(new java.awt.Color(187, 206, 255));
        upload.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        upload.setForeground(new java.awt.Color(0, 0, 0));
        upload.setText("Joindre une photo");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        kGradientPanel1.add(upload);
        upload.setBounds(769, 413, 160, 40);

        Image image = savedImageIcon.getImage();
        Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
        PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        kGradientPanel1.add(PhotoLabel);
        PhotoLabel.setBounds(526, 325, 179, 186);

        Annuler.setBackground(new java.awt.Color(0, 102, 153));
        Annuler.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("Annuler");
        Annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Annuler);
        Annuler.setBounds(930, 580, 102, 39);

        day.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(day);
        day.setBounds(38, 564, 64, 25);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jour");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(38, 542, 64, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mois");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(108, 542, 43, 16);

        month.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(month);
        month.setBounds(108, 564, 64, 25);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Année");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(179, 542, 43, 16);

        year.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(year);
        year.setBounds(178, 564, 64, 25);

        jLabel14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date de Naissance");
        kGradientPanel1.add(jLabel14);
        jLabel14.setBounds(32, 517, 232, 19);

        jLabel15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("fonction");
        kGradientPanel1.add(jLabel15);
        jLabel15.setBounds(770, 230, 220, 19);

        fonction.setBackground(new java.awt.Color(187, 206, 255));
        fonction.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        fonction.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(fonction);
        fonction.setBounds(770, 260, 220, 41);

        jLabel16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Prénom");
        kGradientPanel1.add(jLabel16);
        jLabel16.setBounds(515, 43, 252, 35);

        prenom1.setBackground(new java.awt.Color(187, 206, 255));
        prenom1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        prenom1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(prenom1);
        prenom1.setBounds(515, 84, 252, 39);

        jLabel17.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CIN / N° Passport");
        kGradientPanel1.add(jLabel17);
        jLabel17.setBounds(30, 90, 422, 35);

        cinpassport.setBackground(new java.awt.Color(187, 206, 255));
        cinpassport.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cinpassport.setForeground(new java.awt.Color(0, 0, 0));
        cinpassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinpassportActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cinpassport);
        cinpassport.setBounds(30, 130, 422, 42);

        jLabel18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CNSS");
        kGradientPanel1.add(jLabel18);
        jLabel18.setBounds(270, 510, 180, 35);

        jLabel19.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("type");
        kGradientPanel1.add(jLabel19);
        jLabel19.setBounds(780, 150, 252, 19);

        type.setBackground(new java.awt.Color(187, 206, 255));
        type.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(0, 0, 0));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacataire", "Permenant" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(type);
        type.setBounds(780, 172, 210, 40);

        SaveButton1.setBackground(new java.awt.Color(0, 102, 153));
        SaveButton1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        SaveButton1.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton1.setText("Enregistrer");
        SaveButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(SaveButton1);
        SaveButton1.setBounds(800, 580, 102, 39);

        username1.setBackground(new java.awt.Color(187, 206, 255));
        username1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        username1.setForeground(new java.awt.Color(0, 0, 0));
        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username1);
        username1.setBounds(32, 220, 422, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void FileUploadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileUploadedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileUploadedActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        chooser.setFileFilter(filter);
        int returnValue = chooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            FileUploaded.setText(filename);
            ImageIcon attachedImageIcon = new javax.swing.ImageIcon(filename);
            Image image = attachedImageIcon.getImage();
            Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        } else {
            FileUploaded.setText("");
            Image image = savedImageIcon.getImage();
            Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        }

    }//GEN-LAST:event_uploadActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        
        this.dispose();

    }//GEN-LAST:event_AnnulerActionPerformed

    private void cnssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnssActionPerformed

    private void cinpassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinpassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinpassportActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed
        Enseignant enseignant=new Enseignant();
        String cin_passport=cinpassport.getText();
        int  cnssln=Integer.parseInt(cnss.getText());
        String nomUtilisateur = cnss.getText().trim();
        String emailIn = (email.getText().trim());
        String passwordIn = new String(password.getPassword());
        String nomIn = nom.getText();
        String prenomIn = prenom.getText();
        String telIn = tel.getText();
        int genreIn = genre.getSelectedIndex();
        String photo = FileUploaded.getText();
        String dateNaissance = year.getValue() + "-" + month.getValue() + "-" + day.getValue();
        String typeln=type.getSelectedItem().toString();
        String fonctionln=fonction.getText();
        enseignant.ajouter(cin_passport,nomUtilisateur, emailIn, passwordIn, prenomIn, nomIn, telIn, genreIn, photo, dateNaissance,cnssln,typeln,fonctionln);
        if (enseignant.getCNSS()!=0) {
                    enseignant.consulter(enseignant.getCNSS());

        }
        this.dispose();
    }//GEN-LAST:event_SaveButton1ActionPerformed

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField FileUploaded;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JTextField cinpassport;
    private javax.swing.JTextField cnss;
    private javax.swing.JSpinner day;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fonction;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JSpinner month;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prenom1;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JButton upload;
    private javax.swing.JTextField username1;
    private javax.swing.JSpinner year;
    // End of variables declaration//GEN-END:variables
}
