package Frame;


import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import management.Enseignant;


public class ConsulterEnseignantFrame extends javax.swing.JFrame {

    Enseignant enseignant;
    ImageIcon savedImageIcon = new javax.swing.ImageIcon(getClass().getResource("/photo_profile.jpg"));

   
    public ConsulterEnseignantFrame(Enseignant enseignant ) {
        initComponents();
        this.enseignant = enseignant;
        cin_passport.setText(enseignant.getCIN_Passport());
        username.setText(enseignant.getNomUtilisateur());
        email.setText(enseignant.getEmail());
        password.setText(enseignant.getPassword());
        System.out.println("cnss is "+enseignant.getCNSS());
        System.out.println("birthdya is "+enseignant.getDateNaissance());
        String[] birthday = enseignant.getDateNaissance().split("-");
        day.setValue(Integer.parseInt(birthday[2]));
        month.setValue(Integer.parseInt(birthday[1]));
        year.setValue(Integer.parseInt(birthday[0]));
        cnss.setText(Integer.toString(enseignant.getCNSS()));
        prenom.setText(enseignant.getPrenom());
        nom.setText(enseignant.getNom());
        genre.setSelectedIndex(enseignant.getGenre());
        tel.setText(enseignant.getTel());
        fonction.setText(enseignant.getFonction());
        
        if(enseignant.getType()==Enseignant.Type.PERMANENT){
               type.setSelectedIndex(1);
        }else{
             type.setSelectedIndex(0);
        }
             this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        savedImageIcon= new javax.swing.ImageIcon(enseignant.getPhoto());
        Image image = savedImageIcon.getImage();
        Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
        PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cin_passport = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        genre = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        PhotoLabel = new javax.swing.JLabel();
        EditButton = new javax.swing.JButton();
        day = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        year = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fonction = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        cnss = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 156, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(16, 58, 171));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulter un Enseignant");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(32, 43, 416, 45);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CIN / N° Passport");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(32, 106, 422, 35);

        cin_passport.setEditable(false);
        cin_passport.setBackground(new java.awt.Color(187, 206, 255));
        cin_passport.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cin_passport.setForeground(new java.awt.Color(0, 0, 0));
        cin_passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cin_passportActionPerformed(evt);
            }
        });
        cin_passport.setEditable(false);
        kGradientPanel1.add(cin_passport);
        cin_passport.setBounds(32, 147, 422, 39);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'utilistateur");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(32, 192, 422, 35);

        username.setEditable(false);
        username.setBackground(new java.awt.Color(187, 206, 255));
        username.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.setEditable(false);
        kGradientPanel1.add(username);
        username.setBounds(32, 240, 422, 42);

        email.setEditable(false);
        email.setBackground(new java.awt.Color(187, 206, 255));
        email.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.setEditable(false);
        kGradientPanel1.add(email);
        email.setBounds(32, 333, 422, 39);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(32, 292, 422, 35);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mot de passe");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(32, 378, 422, 35);

        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Prénom");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(515, 43, 190, 35);

        prenom.setEditable(false);
        prenom.setBackground(new java.awt.Color(187, 206, 255));
        prenom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 0, 0));
        prenom.setEditable(false);
        kGradientPanel1.add(prenom);
        prenom.setBounds(515, 84, 190, 39);

        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nom");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(711, 43, 220, 35);

        nom.setEditable(false);
        nom.setBackground(new java.awt.Color(187, 206, 255));
        nom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));
        nom.setEditable(false);
        kGradientPanel1.add(nom);
        nom.setBounds(711, 84, 220, 39);

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Genre");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(515, 157, 190, 19);

        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tél/Mobile");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(710, 350, 220, 19);

        tel.setEditable(false);
        tel.setBackground(new java.awt.Color(187, 206, 255));
        tel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));
        tel.setEditable(false);
        kGradientPanel1.add(tel);
        tel.setBounds(710, 390, 220, 41);

        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Photo");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(515, 240, 76, 38);

        genre.setBackground(new java.awt.Color(187, 206, 255));
        genre.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        genre.setForeground(new java.awt.Color(0, 0, 0));
        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        genre.setEnabled(false);
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        kGradientPanel1.add(genre);
        genre.setBounds(515, 192, 190, 42);

        password.setEditable(false);
        password.setBackground(new java.awt.Color(187, 206, 255));
        password.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setEditable(false);
        kGradientPanel1.add(password);
        password.setBounds(32, 419, 422, 43);

        Image image = savedImageIcon.getImage();
        Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
        PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        kGradientPanel1.add(PhotoLabel);
        PhotoLabel.setBounds(526, 288, 179, 186);

        EditButton.setBackground(new java.awt.Color(0, 102, 153));
        EditButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        EditButton.setForeground(new java.awt.Color(255, 255, 255));
        EditButton.setText("Modifier");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(EditButton);
        EditButton.setBounds(603, 518, 102, 39);

        day.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        day.setEnabled(false);
        day.setEnabled(false);
        kGradientPanel1.add(day);
        day.setBounds(38, 536, 64, 25);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jour");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(38, 514, 64, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mois");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(108, 514, 43, 16);

        month.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        month.setEnabled(false);
        month.setEnabled(false);
        kGradientPanel1.add(month);
        month.setBounds(108, 536, 64, 25);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Année");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(179, 514, 43, 16);

        year.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        year.setEnabled(false);
        year.setEnabled(false);
        kGradientPanel1.add(year);
        year.setBounds(178, 536, 64, 25);

        jLabel14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date de Naissance");
        kGradientPanel1.add(jLabel14);
        jLabel14.setBounds(32, 485, 232, 19);

        jLabel15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CNSS");
        kGradientPanel1.add(jLabel15);
        jLabel15.setBounds(270, 480, 115, 28);

        fonction.setEditable(false);
        fonction.setBackground(new java.awt.Color(187, 206, 255));
        fonction.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        fonction.setForeground(new java.awt.Color(0, 0, 0));
        fonction.setEditable(false);
        kGradientPanel1.add(fonction);
        fonction.setBounds(711, 288, 220, 42);

        deleteButton.setBackground(new java.awt.Color(0, 102, 153));
        deleteButton.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Supprimer");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        kGradientPanel1.add(deleteButton);
        deleteButton.setBounds(735, 518, 104, 42);

        cnss.setEditable(false);
        cnss.setBackground(new java.awt.Color(187, 206, 255));
        cnss.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cnss.setForeground(new java.awt.Color(0, 0, 0));
        fonction.setEditable(false);
        kGradientPanel1.add(cnss);
        cnss.setBounds(280, 528, 184, 42);

        jLabel16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Fonction");
        kGradientPanel1.add(jLabel16);
        jLabel16.setBounds(711, 240, 220, 38);

        jLabel19.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("type");
        kGradientPanel1.add(jLabel19);
        jLabel19.setBounds(720, 160, 180, 19);

        type.setBackground(new java.awt.Color(187, 206, 255));
        type.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        type.setForeground(new java.awt.Color(0, 0, 0));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacataire", "Permenant" }));
        type.setEnabled(false);
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(type);
        type.setBounds(720, 190, 190, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cin_passportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cin_passportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cin_passportActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
            ModifierEnseignantFrame tempFrame=new ModifierEnseignantFrame(enseignant);
      this. dispose();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
       
         int option = JOptionPane.showOptionDialog(null, "supprimer l'enseignant  ?", "Warning",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

       if(option==JOptionPane.OK_OPTION){
          
           enseignant.supprimer();
           this.dispose();
           
       }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JTextField cin_passport;
    private javax.swing.JTextField cnss;
    private javax.swing.JSpinner day;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fonction;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JSpinner month;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JTextField username;
    private javax.swing.JSpinner year;
    // End of variables declaration//GEN-END:variables
}
