package Frame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import management.Cours;

public class ConsulterCoursFrame extends javax.swing.JFrame {

 private Cours cours;

    public ConsulterCoursFrame(Cours cours) {
        initComponents();
        this.setResizable(false);
           this.cours=cours;

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        id_JField.setText(Integer.toString(cours.getId()  ));
        nom_JFIELD.setText(cours.getNom());
        duree_JFILED.setText(Float.toString(cours.getDuree()));
        horaire_JFIELD.setText(cours.getHoraireDebut());
        desc_JFIELD1.setText(cours.getDescription());
        idEns_JFIELD.setText(cours.getIdEns());
        idMat_JFIELD.setText(Integer.toString(cours.getIdMat()));
        idSalle_JFILED.setText(Integer.toString(cours.getIdSalle()));
               if(cours.getDay()==Cours.Day.LUNDI)  day_JFIELD.setSelectedIndex(0); 
        else if(cours.getDay()==Cours.Day.MARDI)day_JFIELD.setSelectedIndex(1);
        else if(cours.getDay()==Cours.Day.MERCREDI)day_JFIELD.setSelectedIndex(2);
        else if(cours.getDay()==Cours.Day.JEUDI)day_JFIELD.setSelectedIndex(3);
        else if(cours.getDay()==Cours.Day.VENDREDI)day_JFIELD.setSelectedIndex(4);
        else if(cours.getDay()==Cours.Day.SAMEDI)day_JFIELD.setSelectedIndex(5);
                   this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_JField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nom_JFIELD = new javax.swing.JTextField();
        idMat_JFIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ConsulterAbsence = new javax.swing.JButton();
        Assigner_Ens = new javax.swing.JButton();
        duree_JFILED = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idSalle_JFILED = new javax.swing.JTextField();
        idEns_JFIELD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        desc_JFIELD1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        horaire_JFIELD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Modifier_ROLE1 = new javax.swing.JButton();
        Supprimer_ROLE1 = new javax.swing.JButton();
        Assigner_Salle = new javax.swing.JButton();
        Assigner_Mat = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        day_JFIELD = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setForeground(new java.awt.Color(60, 63, 65));
        kGradientPanel1.setkEndColor(new java.awt.Color(98, 156, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(16, 58, 171));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulter un Cours");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(6, 43, 502, 45);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("identifiant :");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(6, 106, 381, 35);

        id_JField.setEditable(false);
        id_JField.setBackground(new java.awt.Color(187, 206, 255));
        id_JField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        id_JField.setForeground(new java.awt.Color(0, 0, 0));
        id_JField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_JFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(id_JField);
        id_JField.setBounds(6, 153, 370, 39);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nom :");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(6, 198, 381, 35);

        nom_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        nom_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nom_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        nom_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nom_JFIELD);
        nom_JFIELD.setBounds(6, 239, 371, 42);

        idMat_JFIELD.setEditable(false);
        idMat_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        idMat_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idMat_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        idMat_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMat_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idMat_JFIELD);
        idMat_JFIELD.setBounds(430, 240, 320, 39);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("duree  :");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(10, 470, 381, 35);

        ConsulterAbsence.setBackground(new java.awt.Color(0, 102, 153));
        ConsulterAbsence.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        ConsulterAbsence.setForeground(new java.awt.Color(255, 255, 255));
        ConsulterAbsence.setText("Consulter Absence");
        ConsulterAbsence.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        ConsulterAbsence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsulterAbsenceActionPerformed(evt);
            }
        });
        kGradientPanel1.add(ConsulterAbsence);
        ConsulterAbsence.setBounds(442, 510, 150, 39);

        Assigner_Ens.setBackground(new java.awt.Color(0, 102, 153));
        Assigner_Ens.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Assigner_Ens.setForeground(new java.awt.Color(255, 255, 255));
        Assigner_Ens.setText("Assginer");
        Assigner_Ens.setToolTipText("");
        Assigner_Ens.setBorder(null);
        Assigner_Ens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assigner_EnsActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Assigner_Ens);
        Assigner_Ens.setBounds(760, 330, 98, 39);

        duree_JFILED.setEditable(false);
        duree_JFILED.setBackground(new java.awt.Color(187, 206, 255));
        duree_JFILED.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        duree_JFILED.setForeground(new java.awt.Color(0, 0, 0));
        duree_JFILED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duree_JFILEDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(duree_JFILED);
        duree_JFILED.setBounds(10, 510, 369, 39);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("identifiant  du Enseignant:");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(430, 290, 385, 35);

        idSalle_JFILED.setEditable(false);
        idSalle_JFILED.setBackground(new java.awt.Color(187, 206, 255));
        idSalle_JFILED.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idSalle_JFILED.setForeground(new java.awt.Color(0, 0, 0));
        idSalle_JFILED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSalle_JFILEDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idSalle_JFILED);
        idSalle_JFILED.setBounds(432, 153, 320, 39);

        idEns_JFIELD.setEditable(false);
        idEns_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        idEns_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idEns_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        idEns_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEns_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idEns_JFIELD);
        idEns_JFIELD.setBounds(432, 328, 320, 39);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(393, 564, 414, 35);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(416, 564, 385, 35);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(393, 564, 414, 35);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("identifiant  du Salle:");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(430, 110, 385, 35);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("identifiant  du Matiere:");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(430, 200, 385, 35);

        desc_JFIELD1.setEditable(false);
        desc_JFIELD1.setBackground(new java.awt.Color(187, 206, 255));
        desc_JFIELD1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        desc_JFIELD1.setForeground(new java.awt.Color(0, 0, 0));
        desc_JFIELD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_JFIELD1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(desc_JFIELD1);
        desc_JFIELD1.setBounds(6, 328, 369, 39);

        jLabel11.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" description :");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(6, 287, 381, 35);

        horaire_JFIELD.setEditable(false);
        horaire_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        horaire_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        horaire_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        horaire_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaire_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(horaire_JFIELD);
        horaire_JFIELD.setBounds(10, 420, 369, 39);

        jLabel12.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("horaireDebut  :");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(10, 380, 381, 35);

        Modifier_ROLE1.setBackground(new java.awt.Color(0, 102, 153));
        Modifier_ROLE1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Modifier_ROLE1.setForeground(new java.awt.Color(255, 255, 255));
        Modifier_ROLE1.setText("Modifier");
        Modifier_ROLE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        Modifier_ROLE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_ROLE1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Modifier_ROLE1);
        Modifier_ROLE1.setBounds(610, 510, 102, 39);

        Supprimer_ROLE1.setBackground(new java.awt.Color(0, 102, 153));
        Supprimer_ROLE1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Supprimer_ROLE1.setForeground(new java.awt.Color(255, 255, 255));
        Supprimer_ROLE1.setText("Supprimer");
        Supprimer_ROLE1.setBorder(null);
        Supprimer_ROLE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_ROLE1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Supprimer_ROLE1);
        Supprimer_ROLE1.setBounds(730, 510, 98, 39);

        Assigner_Salle.setBackground(new java.awt.Color(0, 102, 153));
        Assigner_Salle.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Assigner_Salle.setForeground(new java.awt.Color(255, 255, 255));
        Assigner_Salle.setText("Assigner");
        Assigner_Salle.setBorder(null);
        Assigner_Salle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assigner_SalleActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Assigner_Salle);
        Assigner_Salle.setBounds(760, 150, 98, 39);

        Assigner_Mat.setBackground(new java.awt.Color(0, 102, 153));
        Assigner_Mat.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Assigner_Mat.setForeground(new java.awt.Color(255, 255, 255));
        Assigner_Mat.setText("Assigner");
        Assigner_Mat.setBorder(null);
        Assigner_Mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Assigner_MatActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Assigner_Mat);
        Assigner_Mat.setBounds(760, 240, 98, 39);

        jLabel13.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jour :");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(430, 380, 381, 35);

        day_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        day_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        day_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        day_JFIELD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUNDI", "MARDI", "MERCREDI", "JEUDI", "VENDREDI", "SAMEDI" }));
        day_JFIELD.setEnabled(false);
        day_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(day_JFIELD);
        day_JFIELD.setBounds(430, 420, 252, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEns_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEns_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEns_JFIELDActionPerformed

    private void idSalle_JFILEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSalle_JFILEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSalle_JFILEDActionPerformed

    private void duree_JFILEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duree_JFILEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duree_JFILEDActionPerformed

    private void Assigner_EnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assigner_EnsActionPerformed


        
                String EnsCIN= JOptionPane.showInputDialog(null, "Entrer l'identifiant(CNSS) du Matiere:");
              
             
         
                    cours.AssignerAEns(EnsCIN);
                    cours.consulter(cours.getId());
                    this.dispose();
             
    }//GEN-LAST:event_Assigner_EnsActionPerformed

    private void ConsulterAbsenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsulterAbsenceActionPerformed
      
        
   
    }//GEN-LAST:event_ConsulterAbsenceActionPerformed

    private void idMat_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMat_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMat_JFIELDActionPerformed

    private void nom_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_JFIELDActionPerformed

    private void id_JFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_JFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_JFieldActionPerformed

    private void desc_JFIELD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_JFIELD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_JFIELD1ActionPerformed

    private void horaire_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaire_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaire_JFIELDActionPerformed

    private void Modifier_ROLE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_ROLE1ActionPerformed
        ModifierCoursFrame tempFrame=new ModifierCoursFrame(cours);
        this.dispose();
    }//GEN-LAST:event_Modifier_ROLE1ActionPerformed

    private void Supprimer_ROLE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_ROLE1ActionPerformed
           int option = JOptionPane.showOptionDialog(null, "supprimer ce cours  ?", "Warning",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

       if(option==JOptionPane.OK_OPTION){
    
                   cours.supprimer();
                   this.dispose();
       }

       
    }//GEN-LAST:event_Supprimer_ROLE1ActionPerformed

    private void Assigner_SalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assigner_SalleActionPerformed
        
        
                String SalleId_text= JOptionPane.showInputDialog(null, "Entrer l'identifiant du Salle:");
                int SalleId=0;
                Boolean validIdFormat=false;
             try {
            
                  SalleId=Integer.parseInt(SalleId_text);
                
                  if(SalleId==cours.getIdSalle())return;
                  validIdFormat=true;
             
                 
        } catch (Exception e) {
            
        JOptionPane.showMessageDialog(null, "identifiant Salle invalide !", "warning", JOptionPane.INFORMATION_MESSAGE);
            
        }
             if(validIdFormat){
                    cours.AssignerASalle(SalleId);
                    cours.consulter(cours.getId());
                    this.dispose();
             }
          
        
        
    }//GEN-LAST:event_Assigner_SalleActionPerformed

    private void Assigner_MatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Assigner_MatActionPerformed
        
        

        
                String MatId_text= JOptionPane.showInputDialog(null, "Entrer l'identifiant du Matiere:");
                int MatId=0;
                Boolean validIdFormat=false;
             try {
            
                  MatId=Integer.parseInt(MatId_text);
                
                  if(MatId==cours.getIdMat())return;
                  validIdFormat=true;
             
                 
        } catch (Exception e) {
            
        JOptionPane.showMessageDialog(null, "identifiant Matiere invalide !", "warning", JOptionPane.INFORMATION_MESSAGE);
            
        }
             if(validIdFormat){
                    cours.AssignerAMat(MatId);
                    cours.consulter(cours.getId());
                    this.dispose();
             }
        
        
    }//GEN-LAST:event_Assigner_MatActionPerformed

    private void day_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day_JFIELDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assigner_Ens;
    private javax.swing.JButton Assigner_Mat;
    private javax.swing.JButton Assigner_Salle;
    private javax.swing.JButton ConsulterAbsence;
    private javax.swing.JButton Modifier_ROLE1;
    private javax.swing.JButton Supprimer_ROLE1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> day_JFIELD;
    private javax.swing.JTextField desc_JFIELD1;
    private javax.swing.JTextField duree_JFILED;
    private javax.swing.JTextField horaire_JFIELD;
    private javax.swing.JTextField idEns_JFIELD;
    private javax.swing.JTextField idMat_JFIELD;
    private javax.swing.JTextField idSalle_JFILED;
    private javax.swing.JTextField id_JField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField nom_JFIELD;
    // End of variables declaration//GEN-END:variables

}
