/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JOptionPane;
import management.Absence;

/**
 *
 * @author Ahmed
 */
public class ConsulterAbsenceFrame extends javax.swing.JFrame {

    Absence Ab;

    /**
     * Creates new form ConsulterAbsenceFrame
     *
     * @param Ab
     */
    public ConsulterAbsenceFrame(Absence Ab) {
        initComponents();
        this.Ab = Ab;
        IdE.setText(Ab.getIdE());
        IdC.setText(Integer.toString(Ab.getIdC()));
        if (Ab.isJustifie()) {
            Justification.setText(Ab.getJustification());
            gererJus.setText("Supprimer Jus.");
        } else {
            gererJus.setText("Ajouter Jus.");
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IdELabel = new javax.swing.JLabel();
        IdE = new javax.swing.JTextField();
        IdC = new javax.swing.JTextField();
        IdCLabel = new javax.swing.JLabel();
        Justification = new javax.swing.JTextField();
        JustificationLabel = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        gererJus = new javax.swing.JButton();
        SuppBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 129, 255));
        jPanel1.setForeground(new java.awt.Color(22, 129, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tCampus-125.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consulter une Absence");

        IdELabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        IdELabel.setForeground(new java.awt.Color(255, 255, 255));
        IdELabel.setText("Identifiant de l'Etudiant (CIN/Passport)");

        IdE.setBackground(new java.awt.Color(138, 192, 255));
        IdE.setBorder(null);

        IdC.setBackground(new java.awt.Color(138, 192, 255));
        IdC.setBorder(null);

        IdCLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        IdCLabel.setForeground(new java.awt.Color(255, 255, 255));
        IdCLabel.setText("Identifiant de Cours");

        Justification.setBackground(new java.awt.Color(138, 192, 255));
        Justification.setBorder(null);

        JustificationLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        JustificationLabel.setForeground(new java.awt.Color(255, 255, 255));
        JustificationLabel.setText("Justification");

        message.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));

        gererJus.setBackground(new java.awt.Color(138, 192, 255));
        gererJus.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        gererJus.setForeground(new java.awt.Color(18, 66, 129));
        gererJus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gererJusActionPerformed(evt);
            }
        });

        SuppBtn.setBackground(new java.awt.Color(138, 192, 255));
        SuppBtn.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        SuppBtn.setForeground(new java.awt.Color(18, 66, 129));
        SuppBtn.setText("Supprimer");
        SuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppBtnActionPerformed(evt);
            }
        });

        IdE.setEditable(false);
        IdC.setEditable(false);
        Justification.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IdELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdE)
                            .addComponent(IdCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdC, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(JustificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Justification, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(gererJus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(SuppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(IdELabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdE, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdCLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IdC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JustificationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Justification, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SuppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(gererJus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppBtnActionPerformed
        int result = JOptionPane.showOptionDialog(null,
                "Voulez-vous continuer ?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Oui", "Non"},
                "Non");

        if (result == JOptionPane.YES_OPTION) {
            Ab.supprimer();
            this.dispose();
        }
    }//GEN-LAST:event_SuppBtnActionPerformed

    private void gererJusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gererJusActionPerformed
        if (!Ab.isJustifie()) {
            String input = JOptionPane.showInputDialog(null, "Entrez une justification:", "Input Dialog", JOptionPane.QUESTION_MESSAGE);

            if (input != null) {
                Ab.ajouterJustificatif(input);
                Ab.Consulter(Ab.getIdE(), Ab.getIdC());
                this.dispose();
            }
        } else {
            Ab.supprimerJustificatif();
            Ab.Consulter(Ab.getIdE(), Ab.getIdC());
            this.dispose();
        }
    }//GEN-LAST:event_gererJusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdC;
    private javax.swing.JLabel IdCLabel;
    private javax.swing.JTextField IdE;
    private javax.swing.JLabel IdELabel;
    private javax.swing.JTextField Justification;
    private javax.swing.JLabel JustificationLabel;
    private javax.swing.JButton SuppBtn;
    private javax.swing.JButton gererJus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
