/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import management.Groupe;

/**
 *
 * @author Ahmed
 */
public class EditGroupeFrame extends javax.swing.JFrame {

    Groupe GRP;

    /**
     * Creates new form EditGroupeFrame
     */
    public EditGroupeFrame(Groupe G) {
        initComponents();
        this.GRP = GRP;
        IdGRP.setText(Integer.toString(GRP.getId()));
        NomGRP.setText(GRP.getNom());
        NumGRP.setText(Integer.toString(GRP.getNum()));
        IdC.setText(Integer.toString(GRP.getIdC()));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IdGLabel = new javax.swing.JLabel();
        IdGRP = new javax.swing.JTextField();
        NomGRP = new javax.swing.JTextField();
        NomGRPLabel = new javax.swing.JLabel();
        NumGRP = new javax.swing.JTextField();
        NumGRPLabel = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        IdC = new javax.swing.JTextField();
        IdClabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(80, 107, 208));
        jPanel3.setForeground(new java.awt.Color(22, 129, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tCampus-125.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ajouter un Groupe");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IdGLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        IdGLabel.setForeground(new java.awt.Color(255, 255, 255));
        IdGLabel.setText("Identifiant Groupe");

        IdGRP.setBackground(new java.awt.Color(204, 204, 204));
        IdGRP.setForeground(new java.awt.Color(0, 0, 0));
        IdGRP.setBorder(null);
        IdGRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdGRPKeyTyped(evt);
            }
        });

        NomGRP.setBackground(new java.awt.Color(204, 204, 204));
        NomGRP.setBorder(null);
        NomGRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomGRPKeyTyped(evt);
            }
        });

        NomGRPLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        NomGRPLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomGRPLabel.setText("Nom du Groupe");

        NumGRP.setBackground(new java.awt.Color(204, 204, 204));
        NumGRP.setBorder(null);
        NumGRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumGRPKeyTyped(evt);
            }
        });

        NumGRPLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        NumGRPLabel.setForeground(new java.awt.Color(255, 255, 255));
        NumGRPLabel.setText("Num du Groupe");

        message2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        message2.setForeground(new java.awt.Color(255, 255, 255));

        SaveBtn.setBackground(new java.awt.Color(204, 204, 204));
        SaveBtn.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(18, 66, 129));
        SaveBtn.setText("Ajouter");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        IdC.setBackground(new java.awt.Color(204, 204, 204));
        IdC.setBorder(null);
        IdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCActionPerformed(evt);
            }
        });
        IdC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdCKeyTyped(evt);
            }
        });

        IdClabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        IdClabel.setForeground(new java.awt.Color(255, 255, 255));
        IdClabel.setText("Identifiant Classe");

        IdGRP.setEditable(false);
        IdC.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(IdGRP)
                                    .addComponent(IdGLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(NomGRPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NomGRP)
                                    .addComponent(NumGRPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumGRP)
                                    .addComponent(IdClabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdC)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdGLabel)
                .addGap(15, 15, 15)
                .addComponent(IdGRP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NomGRPLabel)
                .addGap(15, 15, 15)
                .addComponent(NomGRP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(NumGRPLabel)
                .addGap(15, 15, 15)
                .addComponent(NumGRP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(IdClabel)
                .addGap(15, 15, 15)
                .addComponent(IdC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161)
                .addComponent(message2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdGRPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdGRPKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_IdGRPKeyTyped

    private void NomGRPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomGRPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NomGRPKeyTyped

    private void NumGRPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumGRPKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_NumGRPKeyTyped

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        if (this.verifCoordonnees() == -1) {
            return;
        }
        String NomGRPIn = NomGRP.getText().trim();
        int NumGRPIn = Integer.valueOf(NumGRP.getText());
        GRP.modifier(NomGRPIn, NumGRPIn);
        GRP.Consulter(GRP.getId());
        this.dispose();
    }//GEN-LAST:event_SaveBtnActionPerformed
    public int verifCoordonnees() {
        String NomGRPIn = NomGRP.getText().trim();
        int NumGRPIn = Integer.valueOf(NumGRP.getText());
        if (NumGRPIn <= 0) {
            displayError("Num de groupe doit être strictement positive");
            return -1;
        }
        if (NomGRPIn.length() == 0) {
            displayError("Vous devez donner un nom");
            return -1;
        }

        return 0;
    }

    public void displayError(String reason) {
        JFrame frame = new JFrame("Error Dialog");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JOptionPane.showMessageDialog(frame, reason, "Erreur", JOptionPane.ERROR_MESSAGE);

        frame.dispose();
    }
    private void IdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCActionPerformed

    private void IdCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdCKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_IdCKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdC;
    private javax.swing.JLabel IdClabel;
    private javax.swing.JLabel IdGLabel;
    private javax.swing.JTextField IdGRP;
    private javax.swing.JTextField NomGRP;
    private javax.swing.JLabel NomGRPLabel;
    private javax.swing.JTextField NumGRP;
    private javax.swing.JLabel NumGRPLabel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel message2;
    // End of variables declaration//GEN-END:variables
}
