package Frame;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import management.Cours;

public class ModifierCoursFrame extends javax.swing.JFrame {

   Cours cours;

    public ModifierCoursFrame(Cours cours) {
        
     
        initComponents();
        this.setResizable(false);
        this.cours=cours;
       
     
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        id_JField.setText(Integer.toString(cours.getId()  ));
        nom_JFIELD.setText(cours.getNom());
        duree_JFILED.setText(Float.toString(cours.getDuree()));
             SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm");
        horaire_JFIELD.setText(dateFormat.format(cours.getHoraireDebut()));
        idEns_JFIELD.setText(Integer.toString(cours.getIdEns()));
        idMat_JFIELD.setText(Integer.toString(cours.getIdMat()));
        idSalle_JFILED.setText(Integer.toString(cours.getIdSalle()));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_JField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nom_JFIELD = new javax.swing.JTextField();
        idMat_JFIELD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        duree_JFILED = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idSalle_JFILED = new javax.swing.JTextField();
        idEns_JFIELD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        desc_JFIELD1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        horaire_JFIELD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Modifier_ROLE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setForeground(new java.awt.Color(60, 63, 65));
        kGradientPanel1.setkEndColor(new java.awt.Color(98, 156, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(16, 58, 171));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modifier un Cours");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(6, 43, 502, 45);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("identifiant :");
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(6, 106, 381, 35);

        id_JField.setEditable(false);
        id_JField.setBackground(new java.awt.Color(187, 206, 255));
        id_JField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        id_JField.setForeground(new java.awt.Color(0, 0, 0));
        id_JField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_JFieldActionPerformed(evt);
            }
        });
        kGradientPanel1.add(id_JField);
        id_JField.setBounds(6, 153, 370, 39);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("nom :");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(6, 198, 381, 35);

        nom_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        nom_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nom_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        nom_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nom_JFIELD);
        nom_JFIELD.setBounds(6, 239, 371, 42);

        idMat_JFIELD.setEditable(false);
        idMat_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        idMat_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idMat_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        idMat_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMat_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idMat_JFIELD);
        idMat_JFIELD.setBounds(430, 240, 369, 39);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("duree  :");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(10, 470, 381, 35);

        Annuler.setBackground(new java.awt.Color(0, 102, 153));
        Annuler.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("Annuler");
        Annuler.setActionCommand("Annuler");
        Annuler.setBorder(null);
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Annuler);
        Annuler.setBounds(730, 510, 98, 39);

        duree_JFILED.setEditable(false);
        duree_JFILED.setBackground(new java.awt.Color(187, 206, 255));
        duree_JFILED.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        duree_JFILED.setForeground(new java.awt.Color(0, 0, 0));
        duree_JFILED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duree_JFILEDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(duree_JFILED);
        duree_JFILED.setBounds(10, 510, 369, 39);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("identifiant  du Enseignant:");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(430, 290, 385, 35);

        idSalle_JFILED.setEditable(false);
        idSalle_JFILED.setBackground(new java.awt.Color(187, 206, 255));
        idSalle_JFILED.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idSalle_JFILED.setForeground(new java.awt.Color(0, 0, 0));
        idSalle_JFILED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idSalle_JFILEDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idSalle_JFILED);
        idSalle_JFILED.setBounds(432, 153, 369, 39);

        idEns_JFIELD.setEditable(false);
        idEns_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        idEns_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        idEns_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        idEns_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEns_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(idEns_JFIELD);
        idEns_JFIELD.setBounds(432, 328, 369, 39);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(393, 564, 414, 35);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(416, 564, 385, 35);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("identifiant  du Classe:");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(393, 564, 414, 35);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("identifiant  du Salle:");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(430, 110, 385, 35);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("identifiant  du Matiere:");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(430, 200, 385, 35);

        desc_JFIELD1.setBackground(new java.awt.Color(187, 206, 255));
        desc_JFIELD1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        desc_JFIELD1.setForeground(new java.awt.Color(0, 0, 0));
        desc_JFIELD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_JFIELD1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(desc_JFIELD1);
        desc_JFIELD1.setBounds(6, 328, 369, 39);

        jLabel11.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" description :");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(6, 287, 381, 35);

        horaire_JFIELD.setEditable(false);
        horaire_JFIELD.setBackground(new java.awt.Color(187, 206, 255));
        horaire_JFIELD.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        horaire_JFIELD.setForeground(new java.awt.Color(0, 0, 0));
        horaire_JFIELD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaire_JFIELDActionPerformed(evt);
            }
        });
        kGradientPanel1.add(horaire_JFIELD);
        horaire_JFIELD.setBounds(10, 420, 369, 39);

        jLabel12.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("horaireDebut  :");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(10, 380, 381, 35);

        Modifier_ROLE1.setBackground(new java.awt.Color(0, 102, 153));
        Modifier_ROLE1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Modifier_ROLE1.setForeground(new java.awt.Color(255, 255, 255));
        Modifier_ROLE1.setText("Modifier");
        Modifier_ROLE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        Modifier_ROLE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_ROLE1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Modifier_ROLE1);
        Modifier_ROLE1.setBounds(610, 510, 102, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEns_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEns_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEns_JFIELDActionPerformed

    private void idSalle_JFILEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idSalle_JFILEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idSalle_JFILEDActionPerformed

    private void duree_JFILEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duree_JFILEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duree_JFILEDActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed

      dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void idMat_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMat_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMat_JFIELDActionPerformed

    private void nom_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_JFIELDActionPerformed

    private void id_JFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_JFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_JFieldActionPerformed

    private void desc_JFIELD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_JFIELD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_JFIELD1ActionPerformed

    private void horaire_JFIELDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaire_JFIELDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaire_JFIELDActionPerformed

    private void Modifier_ROLE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_ROLE1ActionPerformed
        
        
              SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm");
      
       try {
           cours.modifier(nom_JFIELD.getText(),desc_JFIELD1.getText(),Float.parseFloat(duree_JFILED.getText()) , (Date) dateFormat.parse(horaire_JFIELD.getText()));
       } catch (ParseException ex) {
            int option = JOptionPane.showOptionDialog(null, "fomat de date incorrect?", "Warning",
                JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
       }



    }//GEN-LAST:event_Modifier_ROLE1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JButton Modifier_ROLE1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField desc_JFIELD1;
    private javax.swing.JTextField duree_JFILED;
    private javax.swing.JTextField horaire_JFIELD;
    private javax.swing.JTextField idEns_JFIELD;
    private javax.swing.JTextField idMat_JFIELD;
    private javax.swing.JTextField idSalle_JFILED;
    private javax.swing.JTextField id_JField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField nom_JFIELD;
    // End of variables declaration//GEN-END:variables

}
