package Frame;

import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import management.Utilisateur;


public class ModifierUtilisateurFrame extends javax.swing.JFrame {

    Utilisateur utilisateur;
    ImageIcon savedImageIcon = new javax.swing.ImageIcon(getClass().getResource("/photo_profile.jpg"));

    public ModifierUtilisateurFrame(Utilisateur utilisateur) {
        initComponents();
        this.utilisateur = utilisateur;
         cinpassport.setText(utilisateur.getCIN_Passport());
        username.setText(utilisateur.getNomUtilisateur());
        email.setText(utilisateur.getEmail());
        password.setText(utilisateur.getPassword());
        String[] birthday = utilisateur.getDateNaissance().split("-");
        day.setValue(Integer.parseInt(birthday[2]));
        month.setValue(Integer.parseInt(birthday[1]));
        year.setValue(Integer.parseInt(birthday[0]));

        prenom.setText(utilisateur.getPrenom());
        nom.setText(utilisateur.getNom());
        cinpassport.setText(utilisateur.getCIN_Passport()   );
        genre.setSelectedIndex(utilisateur.getGenre());
        tel.setText(utilisateur.getTel());
        
        FileUploaded.setText(utilisateur.getPhoto());
        Image image = savedImageIcon.getImage();
        Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
        PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        FileUploaded = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        upload = new javax.swing.JButton();
        PhotoLabel = new javax.swing.JLabel();
        Annuler = new javax.swing.JButton();
        day = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        month = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        year = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        prenom1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cinpassport = new javax.swing.JTextField();
        SaveButton1 = new javax.swing.JButton();

        setTitle("Modifier un étudiant");
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 156, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(16, 58, 171));
        kGradientPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modifier un Utilisateur");
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 400, 45);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom d'utilistateur");
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(32, 172, 422, 35);

        username.setBackground(new java.awt.Color(187, 206, 255));
        username.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(username);
        username.setBounds(32, 220, 422, 42);

        email.setBackground(new java.awt.Color(187, 206, 255));
        email.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(email);
        email.setBounds(32, 337, 422, 39);

        jLabel4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(32, 290, 422, 35);

        jLabel5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mot de passe");
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(32, 394, 422, 35);

        jLabel6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Prénom");
        kGradientPanel1.add(jLabel6);
        jLabel6.setBounds(515, 43, 252, 35);

        prenom.setBackground(new java.awt.Color(187, 206, 255));
        prenom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(prenom);
        prenom.setBounds(515, 84, 252, 39);

        jLabel7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nom");
        kGradientPanel1.add(jLabel7);
        jLabel7.setBounds(773, 43, 220, 35);

        nom.setBackground(new java.awt.Color(187, 206, 255));
        nom.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(nom);
        nom.setBounds(773, 84, 220, 39);

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Genre");
        kGradientPanel1.add(jLabel8);
        jLabel8.setBounds(515, 147, 252, 19);

        jLabel9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tél/Mobile");
        kGradientPanel1.add(jLabel9);
        jLabel9.setBounds(780, 140, 220, 19);

        tel.setBackground(new java.awt.Color(187, 206, 255));
        tel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(tel);
        tel.setBounds(780, 170, 220, 41);

        jLabel10.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Photo");
        kGradientPanel1.add(jLabel10);
        jLabel10.setBounds(530, 280, 138, 38);

        FileUploaded.setBackground(new java.awt.Color(187, 206, 255));
        FileUploaded.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        FileUploaded.setForeground(new java.awt.Color(0, 0, 0));
        FileUploaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileUploadedActionPerformed(evt);
            }
        });
        kGradientPanel1.add(FileUploaded);
        FileUploaded.setBounds(769, 471, 160, 40);

        genre.setBackground(new java.awt.Color(187, 206, 255));
        genre.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        genre.setForeground(new java.awt.Color(0, 0, 0));
        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Homme", "Femme" }));
        genre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreActionPerformed(evt);
            }
        });
        kGradientPanel1.add(genre);
        genre.setBounds(515, 172, 252, 42);

        password.setBackground(new java.awt.Color(187, 206, 255));
        password.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(password);
        password.setBounds(32, 435, 422, 43);

        upload.setBackground(new java.awt.Color(187, 206, 255));
        upload.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        upload.setForeground(new java.awt.Color(0, 0, 0));
        upload.setText("Joindre une photo");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        kGradientPanel1.add(upload);
        upload.setBounds(769, 413, 160, 40);

        Image image = savedImageIcon.getImage();
        Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
        PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        kGradientPanel1.add(PhotoLabel);
        PhotoLabel.setBounds(526, 325, 179, 186);

        Annuler.setBackground(new java.awt.Color(0, 102, 153));
        Annuler.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        Annuler.setForeground(new java.awt.Color(255, 255, 255));
        Annuler.setText("Annuler");
        Annuler.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Annuler);
        Annuler.setBounds(930, 580, 102, 39);

        day.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(day);
        day.setBounds(38, 564, 64, 25);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jour");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(38, 542, 64, 16);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mois");
        kGradientPanel1.add(jLabel12);
        jLabel12.setBounds(108, 542, 43, 16);

        month.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(month);
        month.setBounds(108, 564, 64, 25);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Année");
        kGradientPanel1.add(jLabel13);
        jLabel13.setBounds(179, 542, 43, 16);

        year.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        kGradientPanel1.add(year);
        year.setBounds(178, 564, 64, 25);

        jLabel14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date de Naissance");
        kGradientPanel1.add(jLabel14);
        jLabel14.setBounds(32, 517, 232, 19);

        jLabel16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Prénom");
        kGradientPanel1.add(jLabel16);
        jLabel16.setBounds(515, 43, 252, 35);

        prenom1.setBackground(new java.awt.Color(187, 206, 255));
        prenom1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        prenom1.setForeground(new java.awt.Color(0, 0, 0));
        kGradientPanel1.add(prenom1);
        prenom1.setBounds(515, 84, 252, 39);

        jLabel17.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CIN / N° Passport");
        kGradientPanel1.add(jLabel17);
        jLabel17.setBounds(30, 90, 422, 35);

        cinpassport.setEditable(false);
        cinpassport.setBackground(new java.awt.Color(187, 206, 255));
        cinpassport.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cinpassport.setForeground(new java.awt.Color(0, 0, 0));
        cinpassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinpassportActionPerformed(evt);
            }
        });
        kGradientPanel1.add(cinpassport);
        cinpassport.setBounds(30, 130, 422, 42);

        SaveButton1.setBackground(new java.awt.Color(0, 102, 153));
        SaveButton1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        SaveButton1.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton1.setText("Enregistrer");
        SaveButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 163, 255)));
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(SaveButton1);
        SaveButton1.setBounds(800, 580, 102, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void FileUploadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileUploadedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FileUploadedActionPerformed

    private void genreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif");
        chooser.setFileFilter(filter);
        int returnValue = chooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            FileUploaded.setText(filename);
            ImageIcon attachedImageIcon = new javax.swing.ImageIcon(filename);
            Image image = attachedImageIcon.getImage();
            Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        } else {
            FileUploaded.setText(utilisateur.getPhoto());
            Image image = savedImageIcon.getImage();
            Image editedImage = image.getScaledInstance(186, 179, Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new javax.swing.ImageIcon(editedImage));
        }

    }//GEN-LAST:event_uploadActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        utilisateur.consulter(utilisateur.getCIN_Passport());
        this.dispose();

    }//GEN-LAST:event_AnnulerActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void cinpassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinpassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinpassportActionPerformed

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed
        String nomUtilisateur = username.getText().trim();
        String emailIn = (email.getText().trim());
        String passwordIn = new String(password.getPassword());
        String nomIn = nom.getText();
        String prenomIn = prenom.getText();
        String telIn = tel.getText();
        int genreIn = (int) genre.getSelectedItem();
        String photo = FileUploaded.getText();
        String dateNaissance = year.getValue() + "-" + month.getValue() + "-" + day.getValue();
        try {
            utilisateur.modifier(nomUtilisateur, emailIn, passwordIn, prenomIn, nomIn, telIn, genreIn, photo, dateNaissance);
        } catch (ParseException ex) {
             int option = JOptionPane.showOptionDialog(null, "Erreur  dans la date de naisence", "Warning",
                    JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
        }
        utilisateur.consulter(utilisateur.getCIN_Passport());
        this.dispose();


    }//GEN-LAST:event_SaveButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField FileUploaded;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JTextField cinpassport;
    private javax.swing.JSpinner day;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JSpinner month;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prenom1;
    private javax.swing.JTextField tel;
    private javax.swing.JButton upload;
    private javax.swing.JTextField username;
    private javax.swing.JSpinner year;
    // End of variables declaration//GEN-END:variables
}
